Basic hammer launch support on Linus
ChaosInitiative/ChaosTools pull request #15
Opened 2021-03-15 23:40 UTC by JJL772

Looking for feedback too; there's a little hack in there and I don't really know a better way to do it.

2021-03-16 10:08 UTC, SpyceTewan requested changes

2021-03-16 10:08 UTC, SpyceTewan commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +        public static string SteamPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) + "/.local/share/Steam/";
Not a fan of hardcoding a platform specific string like that. Should probably create some abstract interface that provides the steam installation or it could also be found out dynamically at runtime

2021-03-16 10:08 UTC, SpyceTewan commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +                var hammerProcessStartInfo = new ProcessStartInfo
Rename hammerProcessStartInfo since it doesn't only start hammer. I know you just copied my name. This is on me

2021-03-16 10:08 UTC, SpyceTewan commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +                    File.Copy(SteamPath + "steamclient.dll", steamDllPath + "/steamclient.dll", overwrite: true);
Use Path.Combine instead of string concatination

2021-03-16 10:08 UTC, SpyceTewan commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +                var process = Process.Start(startInfo);
Is there an async function for this?

2021-03-16 10:08 UTC, SpyceTewan commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +                throw new ToolsLaunchException("Proton 5.13 is not installed");
Hard coded version number

2021-03-16 10:08 UTC, SpyceTewan commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +                    throw new ToolsLaunchException($"Failed to create proton 5.13 prefix at '{directory}");
Hard coded version number again

2021-03-16 10:08 UTC, SpyceTewan commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +                        $"Failed to create proton 5.13 prefix, access to '{directory}' not permitted.");
Hard coded version number

2021-03-16 10:08 UTC, SpyceTewan commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +                    throw new ToolsLaunchException($"Failed to create proton 5.13 prefix at '{directory}'");
Hard coded version number

2021-03-16 10:08 UTC, SpyceTewan commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +            protonStartInfo.Environment.Add("STEAM_COMPAT_CLIENT_INSTALL_PATH", Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) + "/.steam/");
Use Path.Combine

2021-03-16 10:08 UTC, SpyceTewan commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +                prefix = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "/ChaosSDKLauncher";
Use Path.Combine

2021-03-16 16:57 UTC, JJL772 commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +        public static string SteamPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) + "/.local/share/Steam/";
The steam install must always be under `~/.steam/` afaik, and there is no Steamworks.NET API method for finding that path either.

2021-03-16 19:14 UTC, SpyceTewan commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +        public static string SteamPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) + "/.local/share/Steam/";
But that's only for linux

2021-03-16 19:16 UTC, SpyceTewan requested changes

2021-03-16 19:16 UTC, SpyceTewan commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +        public static string ProtonVersion = "Proton 5.13";
The proton version is still hard coded. This will be out of date as soon as proton pushes an update

2021-03-16 23:29 UTC, JJL772 commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +        public static string ProtonVersion = "Proton 5.13";
Proton 5.13 is a specific app on steam. There are apps for Proton 3.7, 4.11, 5.0 and 5.13, that version number is fixed

2021-03-16 23:33 UTC, JJL772 commented on ChaosInitiative.SDKLauncher/Util/ToolsUtil.cs
> +        public static string SteamPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) + "/.local/share/Steam/";
I just renamed it

2021-03-21 17:10 UTC, SpyceTewan approved these changes

2021-03-21 17:10 UTC, merged